name: Scheduled Jobs

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: echo repository name
        run: echo "${{ github.repository }}"

      - name: repository checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: 1day1commit

      - name: Add date and push
        run: |
          cd 1day1commit
          date >> date.txt
          git add .
          git config --global user.email "hw62459930@gmail.com"
          git config --global user.name "HyunWoo9930"
          git commit -am "Inject Date"
          git push

